### ISSUE TITLE
Use SDL2

### ISSUE THREAD

**Issue by calmsacibis995** [emestee/bk-emulator#1]
This emulator uses SDL 1.2, which is obsolete. Albeit I can install SDL 1.2 on my Linux distribution (Ubuntu 20.04), in the near future, it might not be possible to install SDL 1.2 on newer Linux distributions.

**Comment by denisenkom** [comment]
I am looking into upgrade to SDL2 on my fork: https://github.com/denisenkom/bk-emulator/tree/sdl2-upgrade.  I have it compiling and running successfully with SDL2. But display is blank, so more work is needed.  Currently trying to understand how display logic works in order to fix it.

**Comment by emestee** [comment]
SDL2 changed some fundamentals, chiefly the use of SDR_Surface if I remember correctly. 

The display modes and the sigil generation is described in http://bk0010.narod.ru/bkgra 2.1

**Comment by denisenkom** [comment]
I've got display fully working. Keyboard also mostly works except modifier keys like shift don't work, but should be able to fix soon.  It also compiles and runs on Mac.

**Comment by denisenkom** [comment]
Everything seems to work now in Basic and Monitor.  I am trying to test with more software, but cannot figure out how to load it.  I tried using F12 and then providing path to bin file but it is unclear what should be specified as start address.  Tried also loading via Monitor by sending M command and then providing name for the bin file, it seems to load successfully but when I issue S command nothing happens.  I also tried M1000 and then S1000 but that seems to crash CPU and restart into Basic.  I was trying few programs from here: http://bk0010.narod.ru/files.  Can you provide instructions on how to run some program?

**Comment by emestee** [comment]
If you load a binary and `s 1000` command crashes, then something is wrong in the emulator code and has to be debugged. Bear in mind however that in BK world, just like in ZX Spectrum, the more recent software (we're talking 1993 and onwards) had progressive loading, which worked by first loading a loader program from tape which will then read the binary into specific regions of memory, this would often include video memory, and if you try loading such binaries into the emulator I'm not sure it'd work. Desantnik, Tetris, Piton binaries should work reliably.

Try loading binaries from the debugger:

When the emulation is running, you can issue a Ctrl-C in the emulator's console. This will stop the emulation and drop you into the emulator's debugger. To load a game from a binary file (assuming you have one, none are distributed here), do:
`
l <filename> (the emulator will look for the file in /usr/share/bk)`

`g 1000`

If I remember correctly, you can also pass command line arguments into the emulator to load the binary.

**Comment by denisenkom** [comment]
I think something is wrong with the loader, I loaded tetris01.bin via emulator console like so:
```
% l tetris01.bin
LOAD called
Reading tetris01.bin into 001000... Done.
Last filled address is 016666
```
And I did disassembly
```
% a 1000
001000: bic (r5)+, (r4)+
001002: bis (r1), (r4)+
001004: bis (r5), (r1)
001006: bit r4, 46056(r0)
001012: bic r5, r4
001014: cmp r0, -(r0)
001016: cmp r0, -(r0)
001020: mov 16702, sp
001024: jsr pc, 11336
001030: jsr pc, 6170
```
This does not look like a valid program to me. Specifically very first instruction uses r4 and r5 registers as memory pointers and those registers are not initialized.  Unless program expects maybe an OS (Monitor?) to setup those registers in some particular way before jumping to start address.

Can you confirm that this is not what you see when it works?

**Comment by denisenkom** [comment]
I figured it out.  Binary files that I tried contained following header: 2 bytes of start address, 2 bytes of length, 16 bytes of file name.  While this emulator expects only address and length.  After removing file name from the header I was able to load and run some games. So it all looks good.  I will prepare a pull request.

**Comment by denisenkom** [comment]
I think this issue can be resolved

**Comment by toncho11** [comment]
> I figured it out. Binary files that I tried contained following header: 2 bytes of start address, 2 bytes of length, 16 bytes of file name. While this emulator expects only address and length. After removing file name from the header I was able to load and run some games. So it all looks good. I will prepare a pull request.

What did you do exactly? You modified the images? Is it possible to add a command line option that switches to this image format instead of the current expected?

**Comment by denisenkom** [comment]
@toncho11 here is python script which can adjust file header (remove filename from it) to make it load in emulator:

```python
import struct  
  
with open("<file name>", "rb") as f:  
    bytes = f.read()
# Extract header attributes
address, length, name = struct.unpack("HH16s", bytes[:20])  
print(address, length, name)

# Repackage header without file name
new_bytes = struct.pack("HH", address, length) + bytes[20:]  
with open("<file name>.conv", "wb") as f:  
    f.write(new_bytes)
```

**Comment by emestee** [comment]
So there's two types of binaries? The ones I got to work long time ago I can't really remember where they came from.

Can you confirm that the binaries ran through your filter actually work @denisenkom? if so, do I have your permission to drop this script into the repo?

**Comment by denisenkom** [comment]
Yes that script actually worked.  I don't have permissions to push into this repo but you can open a pull request if you like

**Comment by toncho11** [comment]
Thank you @denisenkom ! Can you try with the current version of BK emulator and load a converted binary? Can you point to a specific binary in this format that worked after converting? Having an exact binary image that is known to work will help a lot!

**Comment by denisenkom** [comment]
For example Tetris works, you can download from here: http://bk0010.narod.ru/files/TETRIS01.BIN.gz
Download, unpack, then run python script on it to create TETRIS01.conv, put it in the same folder where you have BK emulator.
Start BK emulator, I used `-1 -c` parameters but other parameters may work too.
In the Basic prompt type `MON` to enter Monitor prompt.
In the Monitor type `M` to initiate load, it will ask for file name, type `TETRIS01.conv` (this file should be placed in the same working folder)
Once load is finished, type `S` to start.  The game should launch.

**Comment by emestee** [comment]
Hello,

I have slightly reworked the conversion tool and it is now included in the master branch as `convert_bkread.py`. You can use it to convert the `bkformat` binaries (such as published on http://bk0010.narod.ru) into something that this emulator can load. I have also updated the readme with instructions. Props to @denisenkom.
