### ISSUE TITLE
Doesn't build in modern environments

### ISSUE THREAD

**Issue by ATroubleshooter** [emestee/bk-emulator#2]
Tried it and received:
```/usr/bin/ld: tty.o:/home-net/alext/Devel/Virtual/bk-emulator/tty.c:55: multiple definition of `pending_interrupts'; service.o:/home-net/alext/Devel/Virtual/bk-emulator/service.c:24: first defined here
collect2: error: ld returned 1 exit status```

After I've added 'extern' into [tty.c](https://github.com/emestee/bk-emulator/blob/master/tty.c) ahead of 'unsigned long pending_interrupts;' everything builds and runs.

**Comment by emestee** [comment]
Patch merged

**Comment by ATroubleshooter** [comment]
@emestee Thank you.
